### ISSUE TITLE
Multiple Subscription Requests

### ISSUE THREAD

**Issue by drok** [boformer/CitiesHarmony#13]
Based on code review, if HarmonyHelper.DoOnHarmonyReady() is called multiple times while the Harmony mod is not already installed, multiple calls to Subscribe will be made. This can happen if one wants to perform multiple Action() when Harmony is ready.

https://github.com/boformer/CitiesHarmony/blob/0cd6b9374efa071f68a8e5d2800f5e5fd835ceff/CitiesHarmony.API/HarmonyHelper.cs#L22

I don't know if PlatformService.workshop.Subscribe() handles duplicate requests well, but they are not necessary and can not lead to anything good.

Also, if a mod is enabled/disabled multiple times while a Subscription is pending, when the subscription finally arrives and _harmonyReadyActions is processed, that mod's requested Actions will be called multiple times. There needs to be a way to clear the mod's enqueued Actions when it is disabled.

**Comment by boformer** [comment]
This has been corrected in the latest API package release (2.0.0). A prompt is now shown to the user (once) and the user can decide to install Harmony, or decline and live with the consequences.

![image](https://user-images.githubusercontent.com/2014500/107887666-5e77c700-6f10-11eb-910e-fac5ac37fac7.png)
