### ISSUE TITLE
Offline breaks the enqueued Action logic

### ISSUE THREAD

**Issue by drok** [boformer/CitiesHarmony#14]
When running offline, without the Workshop, and without Harmony already installed locally, Actions are enqueued in DoOnHarmonyReady(), but the case where Harmony is copied to the folders after the game starts is not handled.

If the Harmony mod is later added to the offline collection, the game will notice it and load it, but the Action queue will not be processed, as the PlatformService.workshop.eventWorkshopItemInstalled is not triggered.

**Comment by boformer** [comment]
I'm accepting a pull request for this, but I don't see it as a high priority as the manual download instructions for this mod on GitHub instruct the user to close the game (see https://github.com/boformer/CitiesHarmony/releases)

Once the game is started again, all local mods should recognize the local CitiesHarmony instance.
