### ISSUE TITLE
Question: any update to Harmony 2.2

### ISSUE THREAD

**Issue by meda22** [boformer/CitiesHarmony#20]
Hi, Just wondering if there is any plan to update to Harmony 2.2 (https://github.com/pardeike/Harmony/releases/tag/v2.2.0.0) or not really? Thanks!

**Comment by boformer** [comment]
I uploaded an rc version of CitiesHarmony.API and CitiesHarmony.Harmony:
https://www.nuget.org/packages/CitiesHarmony.API/2.1.0-rc
it's currently unlisted, but you can install it by running the nuget command or editing the csproj

it only works with the Harmony Experimental workshop item (the stable version is still on 2.0.4).

I plan to push this to a stable channel very soon and release the final nuget packages (no changes, just the nuget package version will change).

Could you test that it works as expected?

**Comment by boformer** [comment]
final version is out, new api is available from nuget
