### ISSUE TITLE
Some people get errors, some dont

### ISSUE THREAD

**Issue by retrievaaaa** [boformer/CitiesHarmony#21]
Hello,
my mod causes problems for some people and for some people it doesn't. Everyone who also has problems tells me they already have Harmony installed, and my friend also has this problem but Steam shows Harmony is installed (it is listed as a mod dependency)

The Exception thrown is:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'CitiesHarmony.API.HarmonyHelper' from assembly 'CollisionBeGoneNET472'.
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception
```

**Comment by boformer** [comment]
Sounds like another mod you have installed (CollisionBeGone??) uses Harmony incorrectly and causes the error.

**Comment by retrievaaaa** [comment]
No no, CollisionBeGone is my mod. But yes, It was because I didn't add the CitiesHarmony.API dll when uploading the mod, so it only worked if other mods had already added it, still thanks for your help!

**Comment by boformer** [comment]
ah, I misread the original issue. Glad you figured it out!
