### ISSUE TITLE
Linux CS players are eagerly awaiting the 2.2-2 upgrade!

### ISSUE THREAD

**Issue by jjl2** [boformer/CitiesHarmony#22]
Hi there!

We Linux CS players have lost the ability to use many mods, and there's reason to believe that Harmony 2.2-2 will fix this.  What news might you have to share regarding any upgrades to CitiesHarmony?  Thanks.

**Comment by JulioQc** [comment]
Dont get your hopes up. I think this is abandoned by the owner considering the silence either here or on steam workshop.

**Comment by boformer** [comment]
It's not abandoned. I will try to release an update after the new DLC is out.

**Comment by JulioQc** [comment]
Oh that's nice thanks :) 
Do you know if 0Harmony upstream fixes those problem under linux or thats still a mystery?

**Comment by boformer** [comment]
Hard to tell. Does the changelog list anything in that regard?

Are we actually sure that the issue started occuring at the same time as the last Harmony mod update came out?

**Comment by jjl2** [comment]
Hi @boformer, thanks for responding and letting us know that this project is still active.  

I believe that your CitiesHarmony project is a branch from:

https://github.com/pardeike/Harmony

The current version number, apparently bumped on July 19, is 2.2.2.  The commit message for https://github.com/pardeike/Harmony/tree/master/Harmony reads:

"adds linux support for struct return buffer checks, adds lambda to CodeMatch".

I'm hoping that means whatever is causing Linux crashes with Harmony has been addressed.

**Comment by JulioQc** [comment]
@boformer any updates?

**Comment by boformer** [comment]
There is a new version on the EXPERIMENTAL version of this mod! It updates the mod to Harmony 2.2.2, which should fix a crash issue for Linux users.

**Note that the EXPERIMENTAL version is only intended for testing!**

https://steamcommunity.com/sharedfiles/filedetails/?id=2399204842

**Comment by boformer** [comment]
please let me know if it fixes the issue. If no other issues are reported, I will push it to the stable channel.

**Comment by JulioQc** [comment]
Amazing! Gave it a quick run and your 2.2.2 release doesn't prevent the game from launching.... but neither does 2.2.1 anymore! 

So my guess is some dependency (Mono? Nvidia? The game itself?) got patched since. Anyhow, I'll go resubscribe all my usual mods and try to play a game on both to compare. I hope to post some feedback within 24-48h if that's ok. 

Either way your update can't hurt and helps to keep the game/community alive, so thank you :)

**Comment by boformer** [comment]
well that's interesting... There were no changes between 2.2-0 and 2.2-1, I only recompiled the mod to remove the compatibility warning in content manager. Could be that something in the game was changed. 

Thanks for reporting back!
