### ISSUE TITLE
Should Harmony work on macOS and Apple Silicon?

### ISSUE THREAD

**Issue by merchako** [boformer/CitiesHarmony#24]
I haven't been able to get any Harmony-dependent mods working on my M1 MacBook Pro. Could you indicate in the README whether Harmony is intended to work on macOS and Apple Silicon? It would help me (and hopefully other users) understand how much work to put into troubleshooting mods.

**Comment by boformer** [comment]
Generally Harmony is platform-independent and should work on Linux and Mac.

**Comment by boformer** [comment]
Do you get any error messages?

**Comment by boformer** [comment]
But yeah it doesn't seem to work on M1 chips because they do not support RMX: https://github.com/pardeike/Harmony/issues/424

There is nothing I can do about it. You might want to look into buying an Intel-based computer.

**Comment by merchako** [comment]
Thank you for the quick response. I can stop trying to hard to get this to work now.

I won't be trying to get an Intel-based computer. Cities: Skylines is frustrating to play without mods, so I'll be waiting for a working path or for Paradox to port Cities: Skylines 2.

**Comment by boformer** [comment]
You can follow this issue: https://github.com/MonoMod/MonoMod/issues/90

Once that has been resolved, we would need to wait for a Harmony library release that includes the patched MonoMod library.

Then I could update this mod.

I have a feeling though it's not going to happen soon.

**Comment by fsimonis** [comment]
@boformer Hi, it looks like Apple Silicon support was added in Harmony 2.4.0.

https://github.com/pardeike/Harmony/releases/tag/v2.4.0.0
