### ISSUE TITLE
Incompatibility: CSUR ToolBox

### ISSUE THREAD

**Issue by boformer** [boformer/CitiesHarmony#7]
https://steamcommunity.com/sharedfiles/filedetails/1959342332

**Comment by pcfantasy** [comment]
@boformer  I know this, I will update this to cityharmony version.

Now it use harmony1.9.9.9 version (local hacked by me)

**Comment by originalfoo** [comment]
Looks like this issue has been resolved.

**Comment by pcfantasy** [comment]
@aubergine10 Yes
