### ISSUE TITLE
No text on UI

### ISSUE THREAD

**Issue by antoine054** [boformer/CitiesHarmony#8]
Hi,
As you may see on Steam Workshop, a lot of players have no text in Cities Skylines since Harmony 2 was released.
Unsubscribing from Network Sins 2 makes it work again. 
Launching the game without Harmony 2 (Airplane Mode) makes it work too. 
Here are my logs. 

A lot of people are mad because of this, me included, dude never release an auto-download mod if you didn't test everything before, or make beta versions beforehand. Thousands of games unplayable today...
Good luck. 
[output_log.txt](https://github.com/boformer/CitiesHarmony/files/4464769/output_log.txt)

**Comment by sombraaa** [comment]
Hello friend,

In the same way as several players reported on the Steam page, i'm also having problems with the letters on Cities Skylines after installing Harmony 2..

**Comment by pcfantasy** [comment]
@sombraaa 

This issue is been solved, if you still have this issue, please send output.log here.

**Comment by sombraaa** [comment]
@pcfantasy 

[output_log.txt](https://github.com/boformer/CitiesHarmony/files/4740967/output_log.txt)

I'm still having this issue, if you could help me, i'll be thankfull.

**Comment by pcfantasy** [comment]
@sombraaa

You still use local mod of transport line manager 13.0(and some other klytes`s mods), which is out of date.

Please use newest mod in steam.
